 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';
require('dotenv').config();
const fs = require('fs');
const express = require('express');
const app = express();
const routes = require('./app/routes');
const bodyParser     = require('body-parser');
const methodOverride = require('method-override');
const mongoose = require('mongoose');
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
const port = process.env.PORT || 8000;

mongoose.connect(process.env.MongodbURL);

const db = mongoose.connection;
db.on('error',console.error.bind(console,'connection error'));
db.once('open', () => {});

app.use(bodyParser.json()); // parse application/json
app.use(bodyParser.json({ type: 'application/vnd.api+json' })); // parse application/vnd.api+json as json
app.use(bodyParser.urlencoded({ extended: true })); // parse application/x-www-form-urlencoded

app.use(methodOverride('X-HTTP-Method-Override')); // override with the X-HTTP-Method-Override header in the request. simulate DELETE/PUT
app.use('/public', express.static(process.cwd() + '/public'));

routes(app);

app.listen(port, function () {
  console.log('Node.js listening ...');
});

exports = module.exports = app;
